server:
  port: 8081

spring:
  jpa:
      open-in-view: false
      show-sql: true
      database-platform: org.hibernate.dialect.H2Dialect
      properties:
        hibernate:
          dialect: org.hibernate.dialect.H2Dialect
      hibernate:
        ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:h2_db
    username: admin
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
